from __future__ import annotations

from datetime import datetime
from pathlib import Path
from textwrap import shorten
from zoneinfo import ZoneInfo

from PIL import Image, ImageDraw, ImageFont

from .calendar_client import CalendarEvent
from .config import AddonConfig


class ScheduleRenderer:
    def __init__(self, config: AddonConfig, output_path: str | Path = "/config/schedule-today.png") -> None:
        self.config = config
        self.output_path = Path(output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self.timezone = ZoneInfo(config.timezone)

    def render(self, events: list[CalendarEvent], now: datetime | None = None) -> Path:
        now = now or datetime.now(self.timezone)
        image = Image.new("RGB", (self.config.image_width, self.config.image_height), "#f7f4ec")
        draw = ImageDraw.Draw(image)

        width, height = image.size
        margin = int(width * 0.07)
        top = int(height * 0.09)
        title_font = load_font(132)
        date_font = load_font(62)
        section_font = load_font(48)
        event_font = load_font(54)
        detail_font = load_font(38)

        draw.rectangle((0, 0, width, height), fill="#f7f4ec")
        draw.line((margin, top + 190, width - margin, top + 190), fill="#2d3a3a", width=4)

        draw.text((margin, top), "Today's Schedule", fill="#1f2a2a", font=title_font)
        draw.text((margin, top + 135), now.strftime("%A, %B %-d"), fill="#52605f", font=date_font)

        all_day = [event for event in events if event.all_day]
        timed = [event for event in events if not event.all_day]

        cursor = top + 265
        if all_day:
            draw.text((margin, cursor), "All Day", fill="#7f4f24", font=section_font)
            cursor += 70
            for event in all_day[:4]:
                draw.text((margin + 42, cursor), shorten(summary(event, self.config.privacy_mode), width=82), fill="#1f2a2a", font=event_font)
                cursor += 78
            cursor += 40

        draw.text((margin, cursor), "Timeline", fill="#7f4f24", font=section_font)
        cursor += 86

        if not timed:
            draw.text((margin + 42, cursor), "No timed events today", fill="#1f2a2a", font=event_font)
        else:
            for event in timed[:13]:
                time_label = event_time_label(event)
                draw.text((margin + 42, cursor), time_label, fill="#52605f", font=detail_font)
                draw.text((margin + 360, cursor - 10), shorten(summary(event, self.config.privacy_mode), width=78), fill="#1f2a2a", font=event_font)
                if event.location and not self.config.privacy_mode:
                    draw.text((margin + 365, cursor + 54), shorten(event.location, width=92), fill="#6e7776", font=detail_font)
                    cursor += 122
                else:
                    cursor += 94

        footer = "Generated by Home Assistant"
        draw.text((margin, height - 120), footer, fill="#87908f", font=detail_font)
        self.output_path.write_bytes(b"")
        image.save(self.output_path, "PNG")
        return self.output_path


def summary(event: CalendarEvent, privacy_mode: bool) -> str:
    return "Busy" if privacy_mode else event.summary


def event_time_label(event: CalendarEvent) -> str:
    if not event.start:
        return ""
    if event.end:
        return f"{event.start.strftime('%-I:%M %p')} - {event.end.strftime('%-I:%M %p')}"
    return event.start.strftime("%-I:%M %p")


def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for path in (
        "/usr/share/fonts/TTF/DejaVuSans.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans.ttf",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
    ):
        try:
            return ImageFont.truetype(path, size=size)
        except OSError:
            continue
    return ImageFont.load_default()
